connection:
  access_token: NWJiMzliMGYtMTIyYS1iMGIwLTNhMjQtZmM5Zi01NGIxMzVmZTozYTllMzY0MC1jNjVmLTExZTgtOGJjZC01ZDNlMmQ1ZDc1NTQ=
  master_host: apimation.com:9000
worker:
  type: 83ed2252-c65f-11e8-a757-6a00020ac460
  port: 9675
  job_limit: 200
  debug: false
  dev: false
  log_path: /Users/dlocmelis/prezentacijas/tapost2018/worker/logs/worker
