connection:
  access_token: NWJiNGFmNGEtYjg2NS0zZGVmLTdjOTgtNTYwMC02ZmI0ZGYyMTpkZjExYjhiMC1jNzAzLTExZTgtOGJjZC01ZDNlMmQ1ZDc1NTQ=
  master_host: apimation.com:9000
worker:
  type: loc
  port: 9675
  job_limit: 200
  debug: false
  dev: false
  log_path: /Users/dlocmelis/prezentacijas/tapost2018/worker/logs/worker
